name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  autoCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto Check
        run: |
          git config --local user.email "392706283@qq.com"
          git config --local user.name "xisuo67"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase origin main
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
